[Service]
Environment=SERVER_ADDRESS=127.0.0.1
Environment=SERVER_PORT=8080
Environment=SERVER_SSL_ENABLED=false
Environment=APP_HTTP_LOOPBACK_PORT=0
Environment=APP_SITE_PUBLIC_URL=http://armageddon.deepspace.ucsb.edu
